- ch4/12_maxflow.ml
Tested with  [SPOJ FASTFLOW](https://www.spoj.com/problems/FASTFLOW/)
> Add Dinic's max flow

- ch6/01_basic_string.py
> Shorten code

- ch6/sa.ml
- ch6/str_align.ml
Suffix array tested on kattis suffixsorting, spoj STRMATCH
> No strings on me

- ch2/fenwicktree_ds.py
- ch2/segmenttree_ds.py
- ch2/unionfind_ds.py
This PR adds three data structures written in Python 3:
- UFDS
- Segment Tree
- Fenwick Tree
> Add Python data structures

- ch2/graph_ds.py
- ch2/priority_queue.py
- ch2/stack_queue.py
This PR adds 3 new libraries in python3:
1. graph_ds
2. priority_queue
3. stack/queue
> Add python3 implementation

- ch3/UVa11742.py
- ch3/UVa12455.py
> Add python code that AC UVa11742 and UVa12455

- ch3/UVa10943.py
Convert to python code for UVa10943
> Add python code for UVa10943

- ch4/bellman_ford.py
- ch4/kruskal_prim.py
Add more Python code for ch4 (Zhi Jian)
> Add more Python code for ch4

- ch4/UVa10004.py
- ch4/UVa10986.py
- ch4/dijkstra.py
- ch4/floyd_warshall.py
Added Python code for UVa10004, UVa10986, Dijkstra and Floyd Warshall (by Zhi Jian).
> Add Python code for ch4

- ch6/str_align.py
Add Python code for ch6 (by Zhi Jian)
> Add Python code for ch6

- ch4/UVa11060.cpp
- ch4/UVa11060.py
Add UVa11060.py and fix incorrect C++ solution for the same problem (by Zhi Jian)
> Add Python solution for UVa11060.py and fix UVa11060.cpp

- ch5/UVa00350.py
- ch5/UVa01230.py
- ch5/UVa10814.py
Add Python solutions for UVa00350, UVa01230, UVa10814 (by Zhi Jian)
> Add Python solutions for ch5

- ch7/points_lines.cpp
> Fix points_line.cpp

- ch3/dp/UVa10130.py
increase recursion limit
no more runtime error
😁
> Fix UVa10130.py

- ch3/dp/UVa10130.py
It's faster than the previous implementation, cleaner code overall.
> Introduce `@lru_cache` to UVa10130.py

- ch2/08_unionfind_ds.ml
I think we should use 1 implementation for consistency @howsiwei
> Extract DSU from Kruskal code

- ch2/lineards/bit_manipulation.cpp
- ch2/lineards/bit_manipulation.java
- ch2/lineards/bit_manipulation.py
- ch8/UVa01079.cpp
- ch8/UVa01079.java
- ch8/UVa01079.ml
Use `lround`, `log2` in c++11, `Math.round` in java and `round`, `math.log2` in python3. Note that `round` in python3 returns `int`(instead of `float`as in python2).
> Use better math functions

- ch2/ourown/fenwicktree_ds.py
In cpbook-code/ch2/ourown/fenwicktree_ds.py line 16, I changed the second j to an i.
> Fenwick Tree Correction

- ch4/mcbm.py
Fix wrong indentation on `ch4/mcbm.py` line `15-16`. Should be indented one step further.
> fix: Fix wrong indentation on mcbm python

- .gitignore
- ch8/maxflow.py
* Document how to use MaxFlow code
* Type annotate functions to be called by user
* Follow PEP for naming, formatting, etc
* Remove call to `main()` that would be executed upon import, instead add it under `if __name__ == '__main__':`
* Add `__repr__` and `copy` to class
* Add copyright notice at top of file
> Type annotate and document ch8/maxflow.py
